name: conan-package

on:
  push:
    paths:
      - 'plugins/**'
      - 'resources/**'
      - 'UM/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'requirements*.txt'
      - '.github/workflows/requirements-runner.txt'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9].[0-9].[0-9]*'
      - '[0-9].[0-9].[0-9]'
      - '[0-9].[0-9][0-9].[0-9]*'

env:
  CONAN_LOGIN_USERNAME_CURA: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD_CURA: ${{ secrets.CONAN_PASS }}

# FIXME: point to `main` once merged
jobs:
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-10831
    with:
      project_name: uranium

  conan-package-export:
    needs: [ conan-recipe-version ]
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-export.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
    secrets: inherit

  conan-package-create-linux:
    needs: [ conan-recipe-version, conan-package-export ]

    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-linux.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      conan_extra_args: '-c tools.build:skip_test=True -o ${{ needs.conan-recipe-version.outputs.project_name }}:enable_i18n=True'
    secrets: inherit