name: conan-package

on:
  push:
    paths:
      - 'plugins/**'
      - 'resources/**'
      - 'UM/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'requirements*.txt'
      - '.github/workflows/requirements-runner.txt'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
      -

jobs:
# FIXME: Use main once merged
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@CURA-11622_conan_v2
    with:
      project_name: uranium
      platform_windows: false
      platform_mac: false
    secrets: inherit
