name: Update translations

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Specific branch to update translations on'
        required: false
        type: string

jobs:
  update-translations:
# FIXME: Use main once merged
    uses: ultimaker/cura-workflows/.github/workflows/update-translations.yml@CURA-11622_conan_v2
      with:
        branch: ${{ inputs.branch }}
